### ISSUE TITLE
Popcorn stops responding while plays the video

### ISSUE THREAD

**Issue by MareLimp** [popcorn-official/popcorn-android#686] opened 2020-07-05 00:06 UTC
Version:  Popcorn Time 2.10 for Arm64 v8a
Download date:  a week ago
Android version:  9.0
Device: Android smart box A95X F3 with Amilogic S905X3 Cortex A55, Mali G31MP, 4GB DDR3 and Android 9.0 Rooted

#### Expected Behaviour
Not to stop responding.

#### Actual Behaviour
After 20+ minutes of playback subtitle freezes, and app stops responding. Video is playing just fine, but I can't pause it or exit the app or do anything. It happens with every video (movie or tv show)

#### Steps to reproduce the behaviour

1. Play any video for more than 20-30 minutes with any subtitle
2. After you notice that the title froze or gone, try to pause the video or to bring up the controls.
3. ...

**Comment by MrRory** [comment] 2020-08-02 21:49
Duplicate of https://github.com/popcorn-official/popcorn-android/issues/486

**Closed by MrRory** 2020-08-02 21:49 UTC
