### ISSUE TITLE
Sub tittles issue

### ISSUE THREAD

**Issue by Kincar-sac** [popcorn-official/popcorn-android#626] opened 2020-04-05 21:13 UTC
Version:  0.2.9
Download date:  05/03/2020
Android version:  9

#### Expected Behaviour

The app runs good but there aren't subtittles or options that allows you yo change the language even for very very old movies as Jurassic park. You can ser only movies on english

#### Actual Behaviour

... It shows all the movies, only in English without subtittles.

#### Steps to repoduce the behaviour

1. ... Enter to the movie 
2. ... Select subtittles
3. ... Always shows as charging subtittles for hours. You can't choose any option. 

Maternal Language: Spanish.

Best Regards!

**Comment by MrRory** [comment] 2020-08-02 21:34
Duplicate of #692

**Closed by MrRory** 2020-08-02 21:34 UTC
