### ISSUE TITLE
Torrent not downloading

### ISSUE THREAD

**Issue by n31043** [popcorn-official/popcorn-android#672] opened 2020-05-20 21:12 UTC
Version:  0.2.10 - arm
Download date:  19/05/2020
Android version:  10

#### Expected Behaviour
Trying to cast a show to Samsung TV (Tizen). Using Oneplus 7T mobile to stream, running Android 10.
...

#### Actual Behaviour
After buffering, streaming begins but shortly after some seconds it stops, keeps buffering and turns impossible to keep streaming. 
Have a 300Mb symetric FTTH internet connection which is stable, TV Is not connected over wifi, is 
connected to cabled ethernet. Dont have a single issue with wifi nor internet.
...

#### Steps to repoduce the behaviour
1. ... Open popcorn time app on mobile
2. ... Select the show to stream
3. ... Select the device to cast the show to
4. ... Begin streaming

**Comment by MrRory** [comment] 2020-08-02 21:25
Duplicate of #247

**Closed by MrRory** 2020-08-02 21:25 UTC
