### ISSUE TITLE
Unable to cast to Chromecast

### ISSUE THREAD

**Issue by zaneperry** [popcorn-official/popcorn-android#607] opened 2020-03-18 23:42 UTC
Version:  0.2.9 ARM
Download date: 3/18/20  
Android version:  10

#### Expected Behaviour

Unable to find Chromecast on cast to screen

#### Actual Behaviour

I see TV models (Like my Roku TV) but no Chromecasts

#### Steps to repoduce the behaviour

1. Open App
2. Click cast to screen
3. No Chromecast present

I am connected to WiFi and can cast from any other app.

**Comment by demetriusqs** [comment] 2020-03-20 23:30
The same problem happens to me

**Comment by MrRory** [comment] 2020-08-02 21:24
Duplicate of #247

**Closed by MrRory** 2020-08-02 21:24 UTC
