### ISSUE TITLE
Chrome cast not being detected

### ISSUE THREAD

**Issue by EberliAugusto** [popcorn-official/popcorn-android#509] opened 2019-03-09 10:15 UTC
Version:  
Download date:  
Android version:  

#### Expected Behaviour

 Most of the times chromecast  is not detected.

#### Steps to repoduce the behaviour
Just open the app on wifi, the chromecast most likely wont be detected.

**Comment by MrRory** [comment] 2019-03-23 17:05
Please fill out the complete issue template, without any info we cannot help you.

Also, duplicate of #58.

**Closed by MrRory** 2019-03-23 17:05 UTC
