### ISSUE TITLE
Chromecast 

### ISSUE THREAD

**Issue by aawarlord** [popcorn-official/popcorn-android#620] opened 2020-04-01 14:34 UTC
Version:  
Download date:  
Android version:  

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to repoduce the behaviour

1. ...normally an icon of chromecast appears when opening the app , having chromecast on a reasonable distance 
2. ... Doesn't see the chromecast even from the same phone I can cast through YouTube or Netflix but not via pop corn time 
3. ... Open chrome cast and app and wait... I believe you will not see the chromecast icon 

May you help me please on those difficult quarantinw days?

**Comment by MrRory** [comment] 2020-08-02 21:24
Duplicate of #247

**Closed by MrRory** 2020-08-02 21:24 UTC
