### ISSUE TITLE
Chromecast icon os not appearing

### ISSUE THREAD

**Issue by nandovicentini** [popcorn-official/popcorn-android#569] opened 2019-09-23 01:39 UTC
Version:  
Download date:  
Android version:  

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to repoduce the behaviour

1. ...
2. ...
3. ...

**Comment by MrRory** [comment] 2020-08-02 21:22
Duplicate of #247

**Closed by MrRory** 2020-08-02 21:22 UTC
