### ISSUE TITLE
Android TV navigation does not work on Android 8.0.0

### ISSUE THREAD

**Issue by ant-1** [popcorn-official/popcorn-android#443] opened 2018-12-27 22:46 UTC
Same as issue https://github.com/popcorn-official/popcorn-android/issues/383

Version:  tv-arm64-v8, build jenkins #161
Download date:  12/27/18
Android version:  Shield TV, Android 8.0.0

#### Expected Behaviour
Having the possibility to select "watch trailer" or "watch EN" from movie card
...

#### Actual Behaviour
No focus on "watch trailer" or "watch EN" from movie card, tried to play with remote clicking on right/left/up/down or OK buttons does nothing
...

#### Steps to repoduce the behaviour

1. From main menu, select "more movies">"trending" (first item) 
2. Select first movie
3. Movie card is displayed but it is not possible to select "watch trailer" or "watch EN"

**Comment by a-haan** [comment] 2018-12-29 14:01
Version 162 fixes Playback but navigation is still broken

**Comment by marcuscarvalho** [comment] 2019-01-02 15:33
@a-haan @ant-1 The navigation is working for me on android tv arm-v7. Can you provide some screenshots or screencast reproducing the issue?

**Comment by ant-1** [comment] 2019-01-03 18:40
@marcuscarvalho Thanks for your commit, it seems to have fixed the playback issue as said @a-haan.

But I'm still not able to navigate on "watch trailer", "watch 1080p" etc... with the remote controller.
Moreover, if I use the shield android app as a mousepad, focus is displayed when I hover the button with the pointer but I need to click two times to launch the playback

I will try to send you a video of the issue

**Comment by MrRory** [comment] 2019-01-04 17:52
This may have something to do with the leanback library being outdated as hell.

**Comment by marcuscarvalho** [comment] 2019-01-04 17:56
Hi, @ant-1 if you can provide a video reproducing the issue would be perfect. Also, let me know more details about your environment/device.  Thanks.

**Comment by marcuscarvalho** [comment] 2019-01-04 17:59
@MrRory I have tested on Android TV v7, may I should test v8 as well? Not sure if leanback library is different between them.

**Comment by MrRory** [comment] 2019-01-04 18:05
I really don't know. I think the implementation is just in the library, so that the Android version doesn't matter. But I'm really not sure.

**Comment by marcuscarvalho** [comment] 2019-01-04 18:36
@Tecko71 can you switch to English language in preferences just to check if the issue persists?

**Comment by marcuscarvalho** [comment] 2019-01-04 18:38
It seems that you are using nvidia shield, what android version is running there?

**Comment by Tecko71** [comment] 2019-01-04 18:39
that is other issue. I can not change language because I can not change settings. When I change settings app crashes.

**Comment by marcuscarvalho** [comment] 2019-01-04 18:39
There is also no focus on Watch Trailer as well

**Comment by marcuscarvalho** [comment] 2019-01-04 18:40
@Tecko71 even with build version 162 you can't change preferences settings?

**Comment by MrRory** [comment] 2019-01-04 18:41
You might need to restart (like fully stop) the app for the language to change.

**Comment by Tecko71** [comment] 2019-01-04 18:41
It is andorid 8.0.0 . Yes even with 162 I can not change settings.

**Comment by Tecko71** [comment] 2019-01-04 18:47
I could only change the language if I change the shield interface to english. But still not able to change settings. Not able to navigate.

**Comment by marcuscarvalho** [comment] 2019-01-04 19:06
@Tecko71 the issue is easily replicated on Android V8.0 Oreo. SDK 26. Thanks for reporting.

**Comment by MrRory** [comment] 2019-01-04 20:58
Okay I think this is a problem because that view is using a copied version of a UI from the leanback library. I think that exists because it was deprecated.

**Comment by MrRory** [comment] 2019-01-04 21:15
Check this PR ^

**Comment by MrRory** [comment] 2019-01-04 21:37
Keeping open until confirmed fixed. I know scrolling doesn't work, but this is the least I could do.

**Comment by Tecko71** [comment] 2019-01-05 12:02
I tried version #168. Navigation problem is solved. Now I can select stream. But settings issue is stil a problem. The app does not crash anymore but chancing settings is not saved. So I can not select subtitle language for example.

**Comment by Tecko71** [comment] 2019-01-05 12:13
build #169 has not all version so I can not test the changes in that build.

**Comment by marcuscarvalho** [comment] 2019-01-05 13:12
The new issue is reported at #465.

You can close this one.

**Comment by MrRory** [comment] 2019-01-05 14:31
Thanks guys

**Closed** 2019-01-05 14:31 UTC

**Comment by a-haan** [comment] 2019-01-06 17:56
@MrRory @marcuscarvalho Movies are working perfectly at the moment other than a minor issue of the background art disappearing when watching a film then pressing back on the remote to go back to the Movie listing.  When you do this the background art is gone.

TV Shows don't work when you first launch the app and pick a show from the 'Latest TV Series' Section they will show 'No synopsis available'. If you then go to 'More Shows' and choose any filter from the list such as 'top rated' and then into a show, the episodes will be present.  you can then go back to the Home screen and the and use the 'Latest TV Series' as expected with all the episodes working.  very strange behaviour.
