### ISSUE TITLE
can not select streams

### ISSUE THREAD

**Issue by Tecko71** [popcorn-official/popcorn-android#453] opened 2019-01-01 15:48 UTC
Version:  #462
Download date:  1-1-2019
Android version  7.2.1 (android tv)
...

#### Actual Behaviour
Can not edit settings, app crashes. Can not select streams. So can not play movie. App is almost done if this issues are fixted

**Comment by marcuscarvalho** [comment] 2019-01-02 15:37
@Tecko71 Can you try the build version 162 and let us know if it works for you?

https://ci.popcorntime.sh/job/Popcorn-Time-Android/162/

**Comment by Tecko71** [comment] 2019-01-02 17:51
I made a mistake I say version 462 but it was version #162 (tv-arm64-v8a-development-162) I am sorry for the mistake. So on the latest version are the errors.

**Comment by MrRory** [comment] 2019-01-04 17:35
Could you edit your post and add more information about what is going wrong exactly? Your current explanation is a bit too broad.

**Comment by MrRory** [comment] 2019-01-04 17:41
I think this issue is a duplicate of #456 for the settings crashes, #457 for the cannot select streams. So I'm closing, let me know if I'm wrong.

**Comment by Tecko71** [comment] 2019-01-04 17:42
when you're selecting the movie you go to the next screen. The screen where you suppose to select 720p or 1080p. Not able to select anything there. So I can not play a movie.

**Closed by MrRory** 2019-01-04 17:41 UTC
Labels: needs info

**Comment by Tecko71** [comment] 2019-01-04 17:43
no it is on version #162 I will make a screenshot

**Comment by marcuscarvalho** [comment] 2019-01-04 17:50
@Tecko71 please provide some screenshots and/or videos with the environment details as well.

**Comment by MrRory** [comment] 2019-01-04 17:50
Yes so the issue is equal to issue #457

**Comment by MrRory** [comment] 2019-01-04 17:53
Maybe even #443?

**Comment by Tecko71** [comment] 2019-01-04 18:17
yes think it is the same issue. Did send you a video link.

**Comment by MrRory** [comment] 2019-01-04 18:19
Can you post the link to the video in issue https://github.com/popcorn-official/popcorn-android/issues/443?
