### ISSUE TITLE
Cannot get tv to cast

### ISSUE THREAD

**Issue by Bradley-99** [popcorn-official/popcorn-android#566] opened 2019-09-20 12:14 UTC
Version:  
Download date:  
Android version:  

#### Expected Behaviour

... Cat from my lg stylo 2 my t. V done there is s car button

#### Actual Behaviour

... Does nothing but bring up the option to connect to my t.v but it does nothing. 

#### Steps to repoduce the behaviour

1. ... Open app
2. ... Hit cast button from a lg stylo 4
3. ... Hit option for casting to t.v and nothing
4. ... Watch it not cast

**Comment by Bradley-99** [comment] 2019-09-20 12:16
Cast* not cat frim ny lg....

I'm going to restart my phone to see if that does anything. I know casting worried in my immune because u checked every other so works. Thank you for your time.

**Comment by Bradley-99** [comment] 2019-09-20 12:17
Cast* not cat frim ny lg....

I'm going to restart my phone to see if that does anything. I know casting works in my immune because u checked every other so works. Thank you for your time.

**Comment by Bradley-99** [comment] 2019-09-20 12:25
Cast* not cat frim ny lg....

I'm going to restart my phone to see if that does anything. I know casting works 9 my immune because u checked every other so works. Thank you for your time.

**Comment by MrRory** [comment] 2020-08-02 21:23
Duplicate of #247

**Closed by MrRory** 2020-08-02 21:23 UTC
