### ISSUE TITLE
Subtitles icon doesn't work!

### ISSUE THREAD

**Issue by ochrisinho** [popcorn-official/popcorn-android#252] opened 2017-07-01 15:38 UTC
Version:  0.2.9 - armeabi-v7a
Download date:  07/01/2017
Android version:  Android 7.0

#### Expected Behaviour
Choose a subtitle language, then watch a movie.

#### Actual Behaviour
The subtitles icon doesn't work. There's no subtitles for any movie.

#### Steps to repoduce the behaviour

1. Choose a movie.
2. Try to click on the subtitles icon.
3. Try to select a language.

**Comment by ChrisAlderson** [comment] 2017-07-30 21:20
Dupe of #192

**Closed by ChrisAlderson** 2017-07-30 21:20 UTC
