### ISSUE TITLE
Latest tv-x86-development Crashes instantly on Nexus Player

### ISSUE THREAD

**Issue by computersteve** [popcorn-official/popcorn-android#138] opened 2017-01-19 14:36 UTC
Version: tv-x86-development-136.apk  
Download date: 1/19/17 
Android version:  7.1.1

#### Expected Behaviour
The app opens to the terms of use after clicking accept and attempting to load the movie thumbnails you are brought back to the home screen with a message saying it crashed. 
...

#### Actual Behaviour
The app crashes with Popcorntime has stopped. 
...

#### Steps to repoduce the behaviour

1. Install latest dev build 
2. Run 
3. Experience the error

**Comment by computersteve** [comment] 2017-01-21 00:01
I downgraded all my Nexus Players to version 0.1.1 which can be found at https://get.popcorntime.sh/repo/build/0.1.1/ ... everything now works except subtitles which is expected because that wasn't fully implemented yet... I hope that the developers of this great app can look at this, and see why this old version works perfectly including trailers, no freezing during video playback on the latest version of android, and no crashing of the app during changing settings inside the app..

**Comment by computersteve** [comment] 2017-01-21 15:19
Ok an update for everyone... I noticed that 1080p streams cause the buffering problem.. meaning you are presented with a constant message of buffering and the torrent never starts to download. If you start a movie on 720p this never seems to happen... Also this older version seems to even have the option for 3D movies something I love since I have a 3D TV, and something that disappeared from the latest version. However the same thing applies to 3D, If you select it you will get constant buffering and the stream won't start =(

**Comment by computersteve** [comment] 2017-01-21 21:33
Also trailers work on these older builds I'm noticing the developers are closing the tickets about trailers but on the latest version of android on my nexus player I'm able to watch all the trailers and all the 720p movie links its the 1080p and 3D that seem to glitch also the streams take forever to load...

**Comment by MrRory** [comment] 2017-01-24 21:02
This is most likely a duplicate of #106

**Comment by MrRory** [comment] 2017-01-24 21:05
Oh and please stop commenting on other issues that are unrelated @computersteve. This is not a forum.

**Comment by MrRory** [comment] 2017-01-24 21:09
Just noticed this explicitly states 'development version' -> they're called development version for a reason. Do not expect them to be stable.

**Closed by MrRory** 2017-01-24 21:09 UTC
