### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by eudobre** [popcorn-official/popcorn-android#363] opened 2018-05-15 11:42 UTC
Version:  2.9
Download date:  18.05.14
Android version:  7.0

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to repoduce the behaviour

1. subtitles don't load 
2. ...
3. ...

**Comment by ChrisAlderson** [comment] 2018-05-15 11:43
Duplicate of #192

**Closed by ChrisAlderson** 2018-05-15 11:43 UTC
