### ISSUE TITLE
Popcorn issue with Chrome Cast.

### ISSUE THREAD

**Issue by Noizin** [popcorn-official/popcorn-android#149] opened 2017-02-03 00:30 UTC
Version:  2.9 (ARM v7 cpu)
Download date:  03/02/2017
Android version:  5.1.1
Device: Vodafone Ultra 6 PT

#### Expected Behaviour
The app should display the cast icon when chromecast is ready to cast and properly configured.

#### Actual Behaviour

Doesn't recognise the Chrome cast, so the app doesn't enable the cast service.

#### Steps to repoduce the behaviour

1. Connect to WiFi with a Chrome cast.
2. Verify if Chrome cast is ready.
3. Open app

**Comment by MrRory** [comment] 2017-02-12 14:21
Duplicate of I don't know how many issues. Primarily #74. Please search before opening a new one.
However, kudos for using to issue template so well :) Not everyone does that.

**Closed by MrRory** 2017-02-12 14:21 UTC

**Comment by Noizin** [comment] 2017-02-13 01:25
Hey MrRory 
Thanks for answering and kudos, even when I didn't notice other many many same issues reposts! I didnt check the closed ones! Ma bad! :)
Well, the issue is not fixed so far, however I manage how to get it done by using YouTube app fist(or any other from Google) then close and open PCT and it's done.. Most of time works at the first try! So far...So good! :)
