### ISSUE TITLE
Chromecast won't connect

### ISSUE THREAD

**Issue by viniciuslmarques** [popcorn-official/popcorn-android#74] opened 2016-11-13 19:47 UTC
Version:0.2.9 -  latest
Download date:  
Android version:  6.0.1

#### Expected Behaviour

... Connect with Chromecast

#### Actual Behaviour

... Didn't show cast connection button

#### Steps to repoduce the behaviour

1. ... Have and Chromecast on
2. ... Open app
3. ... Connect

**Comment by Persei08** [comment] 2016-11-14 16:37
Hi,
Hi,

After some tests done on a reddit discussion ([I can't use chromecast with android app ](https://www.reddit.com/r/PopCornTime/comments/5cr7a7/i_cant_use_chromecast_with_android_app/)), I think you should try to open the app and then turn wifi off/on on your smartphone to see if it help.

**Comment by noeltorious** [comment] 2016-11-18 14:40
GL this issue was opened and had a ton of detail for the same issue and was just closed with no info as to why https://github.com/popcorn-official/popcorn-android/issues/70

**Comment by belumira** [comment] 2016-11-20 18:11
Doesn't work, it actually crashes the app.

**Comment by jjcarloss** [comment] 2016-11-23 17:57
Any old version where chromecast actually works?

**Comment by belumira** [comment] 2016-11-27 14:05
Found a workaround:

1) Open Popcorn
2) Leave the app in the background and open YT
3) Connect to your Chromecast (wait until you see on your TV that YT is ready to cast)
4) Return to Popcorn, then close it (swipe from Recents)
5) Open Popcorn again, you should see the cast icon

DO NOT forget to open Popcorn the first time and go to YT directly. For me at least, it didn't work if I skipped that step.

Hope it works for all!

**Comment by MrRory** [comment] 2017-01-24 21:13
I'm just leaving this issue open for new people coming here. But it is ultimately caused by #83.

**Closed** 2022-06-23 14:40 UTC
