### ISSUE TITLE
The caption is not loading on WebOs and Chromecast

### ISSUE THREAD

**Issue by dassmjf** [popcorn-official/popcorn-android#615] opened 2020-03-29 18:24 UTC
Version:  0.2.9 arm
Download date:  03-26-2020
Android version:  8.0.0

#### Expected Behaviour

I hope the app mirrors the screen of the corresponding movie / series with the appropriate subtitle loaded in the initial settings

#### Actual Behaviour

On the webOs of LG smarts TVs loads the movie, but not the caption in the settings. An error occurs saying "it is not possible to play the video, requiring the app to download more parts". Often the app also crashes and the movie no longer loads.
In ChromeCast there is no loading of the subtitle and sometimes the movie stoping play.

#### Steps to repoduce the behaviour

1. Open app
2. Iniciate a some movie with corresponding caption language
3. Wait your start and time run
4. After, choise the icon Cast (WebOs smart tv or ChromeCast).
5. Then, occurs the error on WebOs and in ChromeCast only the video is show, without the caption, and after a two minutes, the player stop, and app too.

Occurs specifically on "The capter 1 - The Mandalorian" and "Westword - Capter Dissonance Theory".

My cellphone is a Samsung J5, 2Gb Ram. The app is very good, excepcional, but i am having this problem..:(
Thanks!!

**Comment by MrRory** [comment] 2020-08-02 21:24
Duplicate of #247

**Closed by MrRory** 2020-08-02 21:24 UTC
