### ISSUE TITLE
Can't open any genre list

### ISSUE THREAD

**Issue by mylikecookie** [popcorn-official/popcorn-android#152] opened 2017-02-10 02:45 UTC
Version:  0.2.9 - armeabi-v7a
Download date:  10-2-2017
Android version:  6.0.1

#### Expected Behaviour
That it would open the genre i tapped on

#### Actual Behaviour
It did nothing no reaction when tapping the genre
...

#### Steps to repoduce the behaviour

1. Open popcorntime
2. Go to genre
3. Try to select a genre

**Comment by MrRory** [comment] 2017-02-12 14:34
Duplicate of #20

**Closed by MrRory** 2017-02-12 14:34 UTC
