### ISSUE TITLE
TV Shows not working, just show black screen. Movies work with no issues.

### ISSUE THREAD

**Issue by DotingDavid** [popcorn-official/popcorn-android#862] opened 2023-11-02 01:20 UTC
Operating System Version:
AndroidTV - Chromecast - Android TV OS Version 12

Popcorn Time Version:
0.3.6

Download date:
Today

Download url:
https://github.com/popcorn-official/popcorn-android/releases

#### Expected Behaviour
Start connecting to a torrent

#### Actual Behaviour
Return to apps home screen or just show a persistent black screen

#### Steps to reproduce the behaviour
Just launch any tv show

#### Screenshot(s) of issue or error(s) logs (recommended)
It would just show a black screen and nothing else

**Comment by kiriles90** [comment] 2023-11-02 18:45
If this is a general issue and not a seed or a device specific one it probably has to do with whatever the issue is with https://github.com/popcorn-official/popcorn-android/issues/859  

Closing this one since both result with series not being able to play but do join the other issue

**Closed by kiriles90** 2023-11-02 18:45 UTC
