### ISSUE TITLE
Chromecast not detecting and movie filteration tabs don't work

### ISSUE THREAD

**Issue by MDHEXT** [popcorn-official/popcorn-android#491] opened 2019-02-06 23:02 UTC
Version:  2.9
Download date:  unknown
Android version:  8.0

#### Expected Behaviour
App should immediately detect Chromecast and all movies filtration tabs should work

#### Actual Behaviour
Takes app from 5 minutes to infinity to find Chromecast and movie filtration tabs say "something went wrong" search, however works

#### Steps to repoduce the behaviour

1. Open the app
2. Try to use the app

**Comment by MrRory** [comment] 2019-02-08 20:30
I think this is a duplicate of #247 and #478. So I'm closing this. Thanks for reporting.

**Closed by MrRory** 2019-02-08 20:30 UTC
