### ISSUE TITLE
Crashes on Android TV

### ISSUE THREAD

**Issue by madhav-arun** [popcorn-official/popcorn-android#106] opened 2016-12-10 17:47 UTC
Version:  tv-arm64-v8a-development-130
Download date:  11-Dec-2016
Android version:  Android TV 6.0 

#### Expected Behaviour

The App should have played the movie

#### Actual Behaviour

Crashed with error "unfortunatly Popcorntime crashed"

#### Steps to repoduce the behaviour

1. Install the apk
2. open the app and select a movie
3. Click on play EN

**Comment by atheleron** [comment] 2016-12-12 17:49
same here play EN is like some English link to movie usually there is 720p and 1080p link to watch 
the last version that works without crashes is 119 it crashes sometimes but u can watch movies

**Comment by madhav-arun** [comment] 2016-12-15 06:38
Tried Version 135 ,same error.

**Comment by madhav-arun** [comment] 2016-12-15 17:05
Tried Version 135 ,same error.

**Comment by computersteve** [comment] 2017-01-20 02:17
its doing the same exact thing on the nexus player =(

**Comment by nextapprage** [comment] 2017-02-13 05:18
What is your availabille internal storage should have at least 2gbs to keep a stable stream be buffer or APp well crash

**Comment by computersteve** [comment] 2017-02-14 05:21
I have nothing else installed on my device and it still crashed... its something glitchy with the app, I tried it also on the Nexus Player, Nvidia Shield, Razor Forge, & Mii they all crash on the latest development build..

**Comment by nextapprage** [comment] 2017-02-14 07:35
I wonder if it's just bad torrents

**Comment by computersteve** [comment] 2017-02-14 13:58
Internal storage was fine..  on the shield way above 2gbs it was a shield pro, on the forge it was 8, and on the Mii its 3.48, nexus player has about 4gigs, each one crashes on developmental builds, the latest one build that just shows EN instead of 1080p.. and the theory about bad torrents I'm gonna have to say I don't think its that because if you downgrade to 1.0.4 then the movies do play and buffer.. the same movies that crashed the app before.

**Comment by nextapprage** [comment] 2017-02-14 16:09
Yeah I did forget to that I did a magnet download and that played just fine

**Comment by nextapprage** [comment] 2017-02-15 05:49
What development build number was 1.0.4 for Android TV or better yet can
you provide a link to the Download location to the working build thanks

**Comment by conde2** [comment] 2017-02-27 17:29
Same problem with Fire Stick, app crash when trying to play a movie or change the settings

**Comment by computersteve** [comment] 2017-02-27 22:12
Yes the very latest build still crashes... can't try the subtitle fix.. on Android TV Boxes such as Nexus Player, Mii Box, Shield, Forge.

**Comment by Hangman228** [comment] 2017-03-01 14:51
Crash on my box, here is a logcat : 

`3-01 15:36:00.856 2728-2728/pct.droid.tv.dev E/InputEventSender: Exception dispatching finished signal.
03-01 15:36:00.856 2728-2728/pct.droid.tv.dev E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
03-01 15:36:00.858 2728-2728/pct.droid.tv.dev E/MessageQueue-JNI: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String butter.droid.base.providers.media.models.Media$Torrent.getUrl()' on a null object reference
                                                                      at butter.droid.tv.fragments.TVMovieDetailsFragment.onActionClicked(TVMovieDetailsFragment.java:138)
                                                                      at android.support.v17.leanback.widget.PTVDetailsOverviewRowPresenter$ActionsItemBridgeAdapter$1.onClick(PTVDetailsOverviewRowPresenter.java:92)
                                                                      at android.view.View.performClick(View.java:4780)
                                                                      at android.view.View.onKeyUp(View.java:9023)
                                                                      at android.widget.TextView.onKeyUp(TextView.java:5953)
                                                                      at android.view.KeyEvent.dispatch(KeyEvent.java:2643)
                                                                      at android.view.View.dispatchKeyEvent(View.java:8411)
                                                                      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1495)
                                                                      at android.support.v17.leanback.widget.BaseGridView.dispatchKeyEvent(BaseGridView.java:847)
                                                                      at android.support.v17.leanback.widget.HorizontalGridView.dispatchKeyEvent(HorizontalGridView.java:50)
                                                                      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1495)
                                                                      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1495)
                                                                      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1495)
                                                                      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1495)
                                                                      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1495)
                                                                      at android.support.v17.leanback.widget.BaseGridView.dispatchKeyEvent(BaseGridView.java:847)
                                                                      at android.support.v17.leanback.widget.VerticalGridView.dispatchKeyEvent(VerticalGridView.java:40)
                                                                      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1495)
                                                                      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1495)
                                                                      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1495)
                                                                      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1495)
                                                                      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1495)
                                                                      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1495)
                                                                      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1495)
                                                                      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1495)
                                                                      at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchKeyEvent(PhoneWindow.java:2361)
                                                                      at com.android.internal.policy.impl.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1709)
                                                                      at android.app.Activity.dispatchKeyEvent(Activity.java:2702)
                                                                      at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2276)
                                                                      at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4020)
                                                                      at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3982)
                                                                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
                                                                      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
                                                                      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
                                                                      at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3680)
                                                                      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3571)
                                                                      at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3737)
                                                                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
                                                                      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
                                                                      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
                                                                      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3571)
                                                                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
                                                                      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
                                                                      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
                                                                      at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3713)
                                                                      at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:3874)
                                                                      at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2208)
                                                                      at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1849)
                                                                      at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1840)
                                                                    at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinishe
03-01 15:36:00.858 2728-2728/pct.droid.tv.dev D/AndroidRuntime: Shutting down VM
03-01 15:36:00.859 2728-2728/pct.droid.tv.dev E/AndroidRuntime: FATAL EXCEPTION: main
                                                                Process: pct.droid.tv.dev, PID: 2728
                                                                java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String butter.droid.base.providers.media.models.Media$Torrent.getUrl()' on a null object reference
                                                                    at butter.droid.tv.fragments.TVMovieDetailsFragment.onActionClicked(TVMovieDetailsFragment.java:138)
                                                                    at android.support.v17.leanback.widget.PTVDetailsOverviewRowPresenter$ActionsItemBridgeAdapter$1.onClick(PTVDetailsOverviewRowPresenter.java:92)
                                                                    at android.view.View.performClick(View.java:4780)
                                                                    at android.view.View.onKeyUp(View.java:9023)
                                                                    at android.widget.TextView.onKeyUp(TextView.java:5953)
                                                                    at android.view.KeyEvent.dispatch(KeyEvent.java:2643)
                                                                    at android.view.View.dispatchKeyEvent(View.java:8411)
                                                                    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1495)
                                                                    at android.support.v17.leanback.widget.BaseGridView.dispatchKeyEvent(BaseGridView.java:847)
                                                                    at android.support.v17.leanback.widget.HorizontalGridView.dispatchKeyEvent(HorizontalGridView.java:50)
                                                                    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1495)
                                                                    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1495)
                                                                    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1495)
                                                                    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1495)
                                                                    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1495)
                                                                    at android.support.v17.leanback.widget.BaseGridView.dispatchKeyEvent(BaseGridView.java:847)
                                                                    at android.support.v17.leanback.widget.VerticalGridView.dispatchKeyEvent(VerticalGridView.java:40)
                                                                    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1495)
                                                                    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1495)
                                                                    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1495)
                                                                    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1495)
                                                                    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1495)
                                                                    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1495)
                                                                    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1495)
                                                                    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1495)
                                                                    at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchKeyEvent(PhoneWindow.java:2361)
                                                                    at com.android.internal.policy.impl.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1709)
                                                                    at android.app.Activity.dispatchKeyEvent(Activity.java:2702)
                                                                    at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2276)
                                                                    at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4020)
                                                                    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3982)
                                                                    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
                                                                    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
                                                                    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
                                                                    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3680)
                                                                    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3571)
                                                                    at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3737)
                                                                    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
                                                                    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
                                                                    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
                                                                    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3571)
                                                                    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
                                                                    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
                                                                    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
                                                                    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3713)
                                                                    at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:3874)
                                                                    at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2208)
                                                                    at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1849)
                                                                    at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1840)
                                                                    at android.view.inputmethod.I
03-01 15:36:00.861 1539-2032/system_process W/ActivityManager:   Force finishing activity 1 pct.droid.tv.dev/butter.droid.tv.activities.TVMediaDetailActivity`

**Comment by marcuscarvalho** [comment] 2018-12-28 15:46
Fixed on pull request https://github.com/popcorn-official/popcorn-android/pull/444

Anyone can merge it on development? Thanks!

-Marcus

**Comment by marcuscarvalho** [comment] 2018-12-29 11:56
Fixed on android tv, the working build artifact is available at https://ci.popcorntime.sh/job/Popcorn-Time-Android/lastBuild/

**Comment by a-haan** [comment] 2018-12-29 13:47
confirmed now working!

**Comment by a-haan** [comment] 2018-12-29 13:57
https://github.com/popcorn-official/popcorn-android/issues/446 added new issue for Android TV nagivation.

**Closed** 2019-01-04 17:37 UTC
Labels: android tv, bug, help wanted
