### ISSUE TITLE
Chromecast - When video download reach 100%, cast stops.

### ISSUE THREAD

**Issue by hmbto** [popcorn-official/popcorn-android#113] opened 2016-12-12 16:42 UTC
Version: 0.2.9
Download date: Dec 11, 2016
Android version: 7.0

#### Description:
Whenever you're watching a video, when this video is done downloading (reaching 100% donwload) the cast stops, the app cannot reconnect to chromecast due to button disappeared (related to #70 and #74 issues), and cannot continue playing on phone either.

#### Related issues:
#70 #74 

#### Expected Behaviour
When reached 100% download, video should continue playing, cast connection will remain until manual disconnect.
...

#### Actual Behaviour
Cast stops, video does not continue playing on chromecast nor on phone app. To reconnect to chromecast you need to close app and run workaround stated on #74.
...

#### Steps to reproduce the behaviour

1. Open app.
2. Connect to chromecast (see workaround if necessary on #74).
3. Play video - Download will start.

**Comment by MrRory** [comment] 2017-01-24 21:06
I'm closing this as a duplicate of #74. Chromecast support simply just sucks.

**Closed by MrRory** 2017-01-24 21:06 UTC
