### ISSUE TITLE
Audio not work and freeze screen

### ISSUE THREAD

**Issue by rodrigues86** [popcorn-official/popcorn-android#613] opened 2020-03-23 17:01 UTC
Version:  0.2.9
Download date:  23-03-2020
Android version:  10

#### Expected Behaviour
Audio work it;
Movie not freeze sunddelly;

#### Actual Behaviour
- Audio not work on wifi mode casting to other device (phone to TV, for example);
- ongoing of the  movie the screen suddenly freezes

#### Steps to repoduce the behaviour
1 - Cast Twd from phone android to TV

**Comment by MrRory** [comment] 2020-08-02 21:24
Duplicate of #247

**Closed by MrRory** 2020-08-02 21:24 UTC
