### ISSUE TITLE
Chromecast casting unavaliable 

### ISSUE THREAD

**Issue by renataquissak** [popcorn-official/popcorn-android#527] opened 2019-04-28 14:26 UTC
Version:  
Download date:  
Android version:  

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to repoduce the behaviour

1. ...
2. ...
3. ...

**Comment by azizLIGHT** [comment] 2019-05-04 19:21
I think this is a duplicate of #247

**Closed** 2020-08-02 21:17 UTC
