### ISSUE TITLE
DLNA. Cast to TV

### ISSUE THREAD

**Issue by joaovictorlimaal** [popcorn-official/popcorn-android#590] opened 2019-12-26 01:22 UTC
Version:  0.2.9
Download date:  12/25/2019
Android version:  8.0

#### Expected Behaviour
 Cast the movie to my TV (Samsung UN55NU7100).
...

#### Actual Behaviour
 Nothing happens. The app recognizes that my TV exists but doesn't connect.
...

#### Steps to reproduce the behaviour

1. Select a movie and let it start on phone.
2. When it starts, click on the logo to connect with the TV and select.

**Comment by MrRory** [comment] 2020-08-02 21:24
Duplicate of #247

**Closed by MrRory** 2020-08-02 21:24 UTC
