### ISSUE TITLE
Not casting shows 

### ISSUE THREAD

**Issue by khaosdoctor** [popcorn-official/popcorn-android#35] opened 2016-05-31 00:40 UTC
Version:  0.27
Download date:  05.30.2016
Android version:  5.0 Lollipop 

#### Expected Behaviour
Stream show to Google Chrome cast smoothly. 

#### Actual Behaviour

The transmissions started with no sound. Tested with several other shows but all the same results. However, this does not occur with movies, when sound is streaming ok. I also checked if it wasn't my chromecast, but when not streaming (playing internally) the sound is ok. 

The transmissions freezes a lot, like a live loading sort of thing (like when we're watching youtube videos and it stops for loading), but this only happens when streaming and even when the video is fully loaded. 

#### Steps to repoduce the behaviour

1. Open app
2. Open side menu
3. Go to 'shows' 
4. Select a show (I selected game of Thrones) 
5. Connect to chromecast 
6. Play
7. Wait for buffer 
8. When streaming starts it has no sound and it freezes at every second

**Comment by pct-team** [comment] 2016-06-01 07:45
its possible that the video format is not supported by the chromecast device

**Comment by khaosdoctor** [comment] 2016-06-01 13:00
So all shows have incompatible video format? This does not explain much of the issue...

**Comment by brunosaantos** [comment] 2016-06-02 01:45
Same here.

**Comment by pct-team** [comment] 2016-06-05 11:13
if the videofile has an audiostream encoded with AC3 then it's possible that the sound won't work. the chromecast doesnt have the necessary codecs and relies on your tv. if your tv doesnt have the codecs then there is no sound.

**Comment by khaosdoctor** [comment] 2016-06-06 16:11
But what about the freezing behavior?

**Comment by pct-team** [comment] 2016-06-13 21:49
no idea tbh

**Comment by khaosdoctor** [comment] 2016-06-14 13:38
Well then...

**Comment by alioygur** [comment] 2016-06-17 09:39
+1

**Comment by cannnon** [comment] 2016-06-18 10:26
the thing that makes this tricky is that the video's you're watching are actually incomplete. We have the first and last few bytes to make them readable and the rest is downloaded while you're watching. The Chromecast doesnt always seem to like that.

**Comment by khaosdoctor** [comment] 2016-06-18 19:13
The thing I find very strange about this, is that we can cast movies normally like everything is fine. But when casting shows, then this happens. I believe PopcornTime works the same way both for shows and movies, so why is this happening in only one case?

**Comment by cannnon** [comment] 2016-06-22 10:44
codecs? i guess.

**Comment by mourke** [comment] 2016-07-12 23:25
the problem is that movies are .mp4 files and tv shows are .mkv files as two separate API's are used to fetch tv show and movie content. The issue relies in google not fully supporting mkv files. The only way to fix this would be to explicitly set the MIME contentType to "video/mp4" or "video/x-matroska" or "video/webm".

**Comment by khaosdoctor** [comment] 2016-07-13 11:26
But then a conversion would be needed right?

**Comment by mourke** [comment] 2016-07-13 14:22
No, MIME isn't the only way content type is set.

**Comment by cannnon** [comment] 2016-07-24 18:40
@mourke did you test this? i can understand that it would help if the video is h264

**Comment by mourke** [comment] 2016-07-24 18:43
@cannnon well thats how it works in html and js so im presuming this is no different

**Comment by ChrisAlderson** [comment] 2016-10-22 00:01
popcorn-api will pick up some content which is not supported by the Chromecast. Codecs search for are already limited, further limiting can result in a content population which is not significant at all. 

I'm closing this issue because we can't do anything about the codecs on Chromecast, if you the issue with video stuttering still applies you can create a seperate issue for it.

**Closed by ChrisAlderson** 2016-10-22 00:01 UTC
Labels: codec, wontfix
