### ISSUE TITLE
Videos stuck on "waiting for torrent" (Only movies) on Android

### ISSUE THREAD

**Issue by jokhallouf** [popcorn-official/popcorn-android#816] opened 2022-09-14 07:02 UTC
Hey guys,
I've never installed Popcorn time on my Android phone because I have always used it on my Mac since the original popcorn time launches and been updating it since. I just installed it (the latest version 0.3.6) on my OnePlus 8T running android 12 and while the app opens after installing whenever I chose any series to watch it stays on waiting for torrent and never runs (I have a gigabit wifi connection and the same exact videos run without a problem instantaneously on my Mac). I tried watching a movie and it works just fine

**Comment by kiriles90** [comment] 2022-09-14 08:22
Does whatever you are trying to watch have any seeds? (the green/orange/red dot)  

Closing this because if it was an issue with the app everyone would have it (incl you with movies also) but do comment below so we can find the cause of it in this case.

**Closed by kiriles90** 2022-09-14 08:22 UTC

**Comment by rikp777** [comment] 2022-09-19 17:53
Closed?

**Comment by Keemosli** [comment] 2022-09-27 03:04
> Closed?

How was this resolved?

**Comment by jokhallouf** [comment] 2022-09-27 06:16
I deleted the app sorry so many missing features (subtitles, trskt intégration or at least integration with the desktop app to follow what I've watched already) so I don't know if it is resolved or not

**Comment by rikp777** [comment] 2022-09-27 06:20
It seems no one has time or motivation to maintain this repo, Both the Android TV and the app no longer work.

**Comment by kiriles90** [comment] 2022-09-27 10:21
@Keemosli Its resolved by learning what torrents and torrent health (seeds/peers) is.. That's why its closed. The app can make dead torrents magically have seeds.

@rikp777 true, I have enough on my head voluntarily doing it for the desktop app, and Ivan for the desktop and API. No time (and not much experience) for android. If anyone wants to go for it though, by all means, I can merge PRs for you and put a good word so after a while you can get access to merge your own PRs.

**Comment by rikp777** [comment] 2022-09-27 14:09
@kiriles90 I had indeed read the post on Reddit. I myself have no experience with Android development. So probably there are people who can pick this up better. There are many rotten apples so I understand the caution with PRs.
