### ISSUE TITLE
Not able to select sdcard as storage location 

### ISSUE THREAD

**Issue by anandpc** [popcorn-official/popcorn-android#283] opened 2017-09-12 17:15 UTC
Version:  
Download date:  
Android version:  

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to repoduce the behaviour

1. ...
2. ...
3. ...

**Comment by 0b1kn00b** [comment] 2017-10-18 15:00
Found this on android 7

**Comment by ChrisAlderson** [comment] 2018-04-28 19:26
Duplicate of #71

**Closed by ChrisAlderson** 2018-04-28 19:26 UTC
