### ISSUE TITLE
chrome cast

### ISSUE THREAD

**Issue by ConorSurger** [popcorn-official/popcorn-android#605] opened 2020-03-14 08:00 UTC
Version:  0.2.9
Download date: 11 03 2020
Android version:  10

#### Expected Behaviour
Showing the Chrome Cast icon and use it 

#### Actual Behaviour
The app is showing 1% of time the icon of Chrome Cast and the rest of the time nothing. When the icon is on I see just the group to diffuse the sound and not the chrome castvto diffuse the video...

#### Steps to repoduce the behaviour
Turn on all your Chrome Cast device (I've got 2) just go on the app on a Galaxy S10+ ...
Wait few minutes even hours...
If the icon is showing clic on it (I just see the group but not every device)...

**Comment by zaneperry** [comment] 2020-03-18 23:43
Same issue here

**Comment by MrRory** [comment] 2020-08-02 21:24
Duplicate of #247

**Closed by MrRory** 2020-08-02 21:24 UTC
