### ISSUE TITLE
Chromecast button doesn't show up anymore

### ISSUE THREAD

**Issue by NaanTeam** [popcorn-official/popcorn-android#181] opened 2017-02-23 22:57 UTC
Version:  0.2.9 - arm64-v8a
Download date:  Within 6 months, don't remember
Android version:  7.0 Nougat now, used to have Marshmallow LG G5

#### Expected Behaviour
Work with Chromecast.
...

#### Actual Behaviour

...On marshmallow I had an issue with the cast button not showing up when I opened the app. I was usually able to make it appear by toggling the wifi on and off on my phone. It was glitchy and not ideal, but it worked. Now that my phone updated to Nougat I can't get the cast button to show up at all. I'm not sure if I'm just having really bad luck or if my little fix doesn't work anymore. Please look into it. Nothing else about my wifi setup or Chromecast has changed. Cast worked yesterday before my phone updated. Thanks.

#### Steps to repoduce the behaviour

1. ...Open app with wifi switched on and Chromecast/TV turned on and ready to connect
2. ...Cast button doesn't appear...
3. ...Toggle wifi with popcorn time still open and cast button will usually appear (works for marshmallow not Nougat as far as I can tell so far)

**Comment by Breaking1** [comment] 2017-02-24 07:09
Duplicate of #167 and maybe #176

**Closed** 2017-02-24 07:26 UTC

**Comment by askalburgi** [comment] 2018-10-16 06:16
@team-pct I'm still getting this issue 10 months later, is there any progress?
