### ISSUE TITLE
Popcorn App not stable for Android TV

### ISSUE THREAD

**Issue by computersteve** [popcorn-official/popcorn-android#145] opened 2017-01-28 15:13 UTC
Version:  1.4
Download date:  1/28/17
Android version:  6.0.1

#### Expected Behaviour
I love all the work you guys put into the design of the app. It's great looking. However right now its really not usable on Android TV, As the home page of your site says the stable version should be.. I've tried the MiiBox & the Nexus Player both are unstable. 

#### Actual Behaviour
The player crashes, Every time you change a setting in the settings portion the app crashes, Trailers crash the app, Certain movies do not play such as Suicide Squad, Captain America the Winter Soldier. 

Point of this post : 
You guys keep closing all our bug reports & telling us not to post anymore instead of looking into the problems or you blame our internet connection... I switched to the android app created by popcorn-time.to, and now I need to use an Air Mouse, but guess what, the movies always work.. None of these problems.. Plus I can play Captain America & Suicide Squad lol =) I hope you guys start to look into these problems, your app could be great but right now its subpar.

**Comment by nextapprage** [comment] 2017-01-31 14:57
Good luck with ransomware popcorn time (Time 4popcorntime )•io has known and confirmed to be leaked with malware and Ransomware I would be heavily cautious about using any popcorn time forks I know it's Frustrating to deal with all the bugs and the slow load times but I really would be worried about using PT forks.

**Comment by nextapprage** [comment] 2017-01-31 14:58
You can try the Dev beta version of popcorn time for Android TV here https://is.gd/GahesJ

**Comment by MrRory** [comment] 2017-02-12 14:33
> You guys keep closing all our bug reports & telling us not to post anymore instead of looking into the problems or you blame our internet connection

Yes I'm closing issues because they're duplicates of #106. One issue is enough, we don't need multiple that say the same thing. I'm not fixing anything, I don't have time for that. Others can and will if they want to and have time. We're in no way obliged to provide you with a completely stable application. If you find an alternative that works better for you then that's fine. Fixing things just takes time unfortunately.

**Closed** 2017-02-12 14:33 UTC
Labels: duplicate
